### ISSUE TITLE
Is jsConfigure(_ enablePlugins ScalaJSWeb) required

### ISSUE THREAD

**Issue by rgwilton** [vmunier/akka-http-with-scalajs-example#2]
Hi,

I was wondering whether the " jsConfigure(_ enablePlugins ScalaJSWeb)" was required for the shared project, or whether it wouldn't just be OK to use .enablePlugins(ScalaJSWeb)?

Is this just an optimization?  Or is it something deeper?

Kind regards,
Rob

**Comment by vmunier** [comment]
Hi,
Actually, we don't need to enable `ScalaJSWeb` on the shared project anymore, because the SourceMap files will be picked up from the `client` project automatically, which depends on `sharedJs`. I have removed the line from `build.sbt`.
Thanks,
Vincent
